### ISSUE TITLE
"Our Team" section in Home Page is not responsive for large display.

### ISSUE THREAD

**Issue by realsdx** [lugnitdgp/lugnitdgp-website#31]
Photos in this section is not responsive for large display (24 inch, 1920x1080 res).
![screenshot from 2018-11-24 15-49-13](https://user-images.githubusercontent.com/30264618/48967052-32a35a80-f001-11e8-92d6-4d391dc3d6f6.png)

**Comment by SucharuRai** [comment]
I think this issue has been fixed. Pls see to that and close this

**Comment by realsdx** [comment]
Yes! Its fixed.
