### ISSUE TITLE
Modals on team page not being displayed correctly

### ISSUE THREAD

**Issue by arc9693** [lugnitdgp/lugnitdgp-website#64]
### Corrections
- Z-index of modal should be more than nav-menu

![Screenshot from 2020-08-10 13-52-39](https://user-images.githubusercontent.com/36061892/89763759-c936e880-db10-11ea-8fa7-7b0a4449f1e5.png)

**Comment by arc9693** [comment]
@SucharuRai @YASHMAROO Take a look

**Comment by arc9693** [comment]
Same issue with the Alumni page. Also, reduce the text size of names and padding in between consecutive member images. @YASHMAROO

**Comment by SucharuRai** [comment]
It's done!

**Comment by arc9693** [comment]
OK. Looks good. Good work @SucharuRai .Closing this.
