### ISSUE TITLE
Lag while scrolling through the LINIT section of home page.

### ISSUE THREAD

**Issue by noobliman** [lugnitdgp/lugnitdgp-website#68]
Probable relation with background image of Linit in the display area of LINIT section.
Lag experienced on Android devices, the image successfully loads up.
No lag experiences on iPhone, the background image doesn't load up.

**Comment by arc9693** [comment]
@YASHMAROO Can you take this up?

**Comment by YASHMAROO** [comment]
@arc9693 will try to find a solution for the problem.

**Comment by YASHMAROO** [comment]
@arc9693 Sent a PR regarding the above issue please review it.
